KDIR:= /lib/modules/$(shell uname -r)/build
PWD  := $(shell pwd)

obj-m += vdaq.o

ccflags-y += -I$(src)/../../include

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean
